minecraft-server:
  ports:
    - "25565:25565"

  environment:
    EULA: "TRUE"
    VERSION: 1.13
    DIFFICULTY: easy
    WHITELIST: supr_dave
    OPS: supr_dave
    ALLOW_NETHER: "true"
    ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
    ENABLE_COMMAND_BLOCK: "true"
    FORCE_GAMEMODE: "true"
    GENERATE_STRUCTURES: "true"
    SPAWN_ANIMALS: "true"
    SPAWN_MONSTERS: "true"
    SPAWN_NPCS: "true"
    MODE: survival
    PVP: "false"
    SEED: 4031384495743822299

  image: itzg/minecraft-server

  container_name: mc

  tty: true
  stdin_open: true
  restart: always

  volumes:
    - ./data:/data
